# Generated by Django 3.2.4 on 2021-08-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='InvoiceItem',
        ),
    ]
