# Generated by Django 3.2.4 on 2021-08-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0001_initial'),
        ('orders', '0002_rename_orderitem_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addr_ord', to='myusers.address'),
        ),
    ]
