# Generated by Django 3.2.4 on 2021-08-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='_price',
        ),
        migrations.AlterField(
            model_name='book',
            name='_price',
            field=models.BigIntegerField(db_column='price', default=0),
        ),
    ]
