# Generated by Django 3.2.4 on 2021-08-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210819_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
