# Generated by Django 3.2.4 on 2021-08-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_book_discount_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='_price',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
