# Generated by Django 3.2.4 on 2021-08-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210819_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount_book',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
