# Generated by Django 3.2.4 on 2021-08-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_book_discount_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='unit_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
