# Generated by Django 3.2.4 on 2021-08-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_book_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='discount',
            new_name='discount_book',
        ),
    ]
