# Generated by Django 3.2.4 on 2021-08-19 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_discount_book_discount_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount_book',
        ),
    ]
