# Generated by Django 3.2.4 on 2021-08-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('off', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='book',
        ),
        migrations.AddField(
            model_name='discount',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.book'),
            preserve_default=False,
        ),
    ]
