# Generated by Django 3.2.4 on 2021-08-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('off', '0002_auto_20210819_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='book',
        ),
        migrations.AddField(
            model_name='discount',
            name='book',
            field=models.ManyToManyField(related_name='book_off', to='product.Book'),
        ),
    ]
