# Generated by Django 3.2.4 on 2021-08-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210819_0331'),
        ('off', '0003_auto_20210819_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_off', to='product.Book'),
        ),
    ]
